/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.ui;

import crs.EligibilityAndEnrollmentFrames.EligibilityCheckerForm;
import crs.EligibilityAndEnrollmentFrames.EnrollmentForm;
import crs.recovery.gui.FrmCourseRecoveryPlan;
import crs.reporting.ui.FrmAcademicReport;
import javax.swing.JFrame;

//import crs.forms.EnrollmentForm;

/**
 *
 * @author HP
 */
public class AcademicOfficerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcademicOfficerDashboard.class.getName());

    /**
     * Creates new form AcademicOfficerDashboard
     */
    public AcademicOfficerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        course_recovery_plan_btn = new javax.swing.JButton();
        eligibility_check_btn = new javax.swing.JButton();
        performance_report_btn = new javax.swing.JButton();
        ao_exit_btn = new javax.swing.JButton();
        enrolment_btn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 102));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DASHBOARD");

        course_recovery_plan_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        course_recovery_plan_btn.setText("VIEW COURSE RECOVERY PLAN");
        course_recovery_plan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_recovery_plan_btnActionPerformed(evt);
            }
        });

        eligibility_check_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        eligibility_check_btn.setText("ELIGIBILITY CHECK");
        eligibility_check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligibility_check_btnActionPerformed(evt);
            }
        });

        performance_report_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        performance_report_btn.setText("ACADEMIC PERFORMANCE REPORTING");
        performance_report_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performance_report_btnActionPerformed(evt);
            }
        });

        ao_exit_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ao_exit_btn.setText("EXIT");
        ao_exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ao_exit_btnActionPerformed(evt);
            }
        });

        enrolment_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        enrolment_btn.setText("ENROLLMENT");
        enrolment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolment_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(performance_report_btn)
                            .addComponent(course_recovery_plan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enrolment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eligibility_check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(ao_exit_btn)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(course_recovery_plan_btn)
                .addGap(44, 44, 44)
                .addComponent(eligibility_check_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(enrolment_btn)
                .addGap(40, 40, 40)
                .addComponent(performance_report_btn)
                .addGap(51, 51, 51)
                .addComponent(ao_exit_btn)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eligibility_check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligibility_check_btnActionPerformed
        dispose();
        EligibilityCheckerForm EligibilityChecker = new EligibilityCheckerForm();
        EligibilityChecker.setVisible(true);
                 //TODO add your handling code here:
    }//GEN-LAST:event_eligibility_check_btnActionPerformed

    private void ao_exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ao_exit_btnActionPerformed
        dispose();  
        LOGIN_FRAME login = new LOGIN_FRAME();
        login.setVisible(true);
        login.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_ao_exit_btnActionPerformed

    private void enrolment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolment_btnActionPerformed
        dispose();
        EnrollmentForm Enrollment = new EnrollmentForm();
        Enrollment.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_enrolment_btnActionPerformed

    private void performance_report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performance_report_btnActionPerformed
        
        JFrame f = new JFrame("Academic Reporting");
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setContentPane(new crs.reporting.ui.FrmAcademicReport()); 
        f.pack();
        f.setSize(900, 600); 
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        dispose();

    // TODO add your handling code here:
    }//GEN-LAST:event_performance_report_btnActionPerformed

    private void course_recovery_plan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_recovery_plan_btnActionPerformed
        dispose();
        FrmCourseRecoveryPlan courseRecovery = new FrmCourseRecoveryPlan();
        courseRecovery.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_course_recovery_plan_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AcademicOfficerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ao_exit_btn;
    private javax.swing.JButton course_recovery_plan_btn;
    private javax.swing.JButton eligibility_check_btn;
    private javax.swing.JButton enrolment_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton performance_report_btn;
    // End of variables declaration//GEN-END:variables
}
