/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.ui;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import crs.management.TableLoader;

/**
 *
 * @author HP
 */
public class AssignSearchUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AssignSearchUser.class.getName());

    /**
     * Creates new form AssignSearchUser
     */
    
    private AssignCourseFrame parentFrame; 
    private DefaultTableModel model;
    
    
    public AssignSearchUser(crs.ui.AssignCourseFrame form) {
        initComponents();
        this.parentFrame = form;
        
        TableLoader.loadStudentsOnly(assignTable, "data/LOGIN.txt");
        
        model = (DefaultTableModel) assignTable.getModel();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignTable = new javax.swing.JTable();
        assign_search_txt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ENTER USER INFORMATION TO SEARCH FOR USER");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 222, 195));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ENTER STUDENT INFORMATION");

        assignTable.setBackground(new java.awt.Color(245, 225, 205));
        assignTable.setForeground(new java.awt.Color(0, 0, 0));
        assignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STUDENT ID", "FIRST NAME", "LAST NAME", "MAJOR", "YEAR"
            }
        ));
        assignTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignTableMouseClicked(evt);
            }
        });
        assignTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                assignTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(assignTable);

        assign_search_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("ENTER STUDENT DETAILS"));
        assign_search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                assign_search_txtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assign_search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assign_search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTableMouseClicked
        int selectedRow = assignTable.getSelectedRow();
        if (selectedRow != -1) {
            int actualRow = assignTable.convertRowIndexToModel(selectedRow);
            
            // Get User ID from Column 0
            String userId = model.getValueAt(actualRow, 0).toString(); 
            
            // CALL THE POPULATE METHOD in the parent frame
            parentFrame.populateStudentDetails(userId);
            
            this.dispose(); // Close this popup
        }            // TODO add your handling code here:
    }//GEN-LAST:event_assignTableMouseClicked

    private void assignTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_assignTableKeyReleased
//        int selectedRow = assignTable.getSelectedRow();
//        if (selectedRow != -1) {
//            int actualRow = assignTable.convertRowIndexToModel(selectedRow);
//            
//            // Get User ID from Column 0 (Since loadStudentsOnly puts ID first)
//            // Double check your TableLoader columns. 
//            // If TableLoader order is {ID, First, Last...} then ID is index 0.
//            // If TableLoader order is {Role, ID...} then ID is index 1.
//            // Based on my previous code for loadStudentsOnly, ID was index 0.
//            String userId = model.getValueAt(actualRow, 0).toString(); 
//            
//            // 3. CALL THE METHOD IN ASSIGN COURSE FRAME
//            parentFrame.populateStudentDetails(userId);
//            
//            this.dispose(); // Close popup
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_assignTableKeyReleased

    private void assign_search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_assign_search_txtKeyReleased
        String query = assign_search_txt.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        assignTable.setRowSorter(sorter);
        
        if (query.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_assign_search_txtKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignTable;
    private javax.swing.JTextField assign_search_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
