/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crs.reporting.ui;
import java.awt.BorderLayout;

import crs.EligibilityAndEnrollment.EligibilityChecker;
import crs.recovery.io.FileRecoveryPlanRepository;
import crs.recovery.io.RecoveryPlanRepository;
import crs.reporting.service.*;
import crs.reporting.service.impl.*;
/**
 *
 * @author Acer
 */
public class FrmAcademicReport extends javax.swing.JPanel {
    private AcademicReportPanel reportPanel;
    

    /**
     * Creates new form FrmAcademicReport
     */
    public FrmAcademicReport() {
        initComponents();
    
        // Use BorderLayout so our custom panel fills the form
        setLayout(new BorderLayout());

        // 1. Build dependencies (same as in Crs.java)
        EligibilityChecker checker = new EligibilityChecker();
        StudentInfoProvider infoProvider = new StudentInfoProviderImpl(checker);
        StudentResultsProvider resultsProvider = new StudentResultsProviderImpl(checker);
        AcademicReportService reportService = new AcademicReportService(infoProvider, resultsProvider);

        RecoveryPlanRepository repo = new FileRecoveryPlanRepository("recovery_plans.txt");
        RecoveryFeedbackProvider feedbackProvider = new RecoveryFeedbackProviderImpl(repo);

        // 2. Back button action – for now just a placeholder
        Runnable backAction = () -> {
            // Later: switch back to main menu frame or another panel
            System.out.println("Back clicked in FrmAcademicReport");
        };

        // 3. Create your existing custom panel
        reportPanel = new AcademicReportPanel(reportService, feedbackProvider, backAction);

        // 4. Add it into this JPanel Form
        add(reportPanel, BorderLayout.CENTER);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
